[package]
name = "nothingos"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.lazy_static]
version = "1.4.0"
features = ["spin_no_std"]

[profile.dev]
debug-assertions = false

[profile.release]
opt-level = 3 

[features]
test = []

[dependencies]
fmt = "0.1.0"
spin = "0.9.8"
x86_64 = "0.14.11"
pic8259 = "0.10.1"
pc-keyboard = "0.5.0"
uart_16550 = "0.2.0"
bitflags = "2.4.1"
uguid = "2.2.0"
getrandom = { version = "0.2.11", features = ["rdrand"] }
x2apic = "0.4.3"
uefi = "0.27.0"
elf_rs = "0.3.1"
bit_field = "0.10.2"

[dependencies.crc]
version = "1.8.1"
default-features = false

[dependencies.crossbeam-queue]
version = "0.2.1"
default-features = false
features = ["alloc"]

[dependencies.uuid]
version = "1.6.1"
features = ["v4"]
default-features = false

[dependencies.futures-util]
version = "0.3.4"
default-features = false
features = ["alloc", "async-await"]

[dependencies.conquer-once]
version = "0.4.0"
default-features = false

[build-dependencies]
cc = "1.0"
nasm-rs = "0.3.0"
buildid = "=1.0.2"
