[package]
name = "nothingos"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.lazy_static]
version = "1.4.0"
features = ["spin_no_std"]

[profile.dev]
debug-assertions = false

[package.metadata.bootimage]
test-timeout = 300
test-args = [
    "-device", "isa-debug-exit,iobase=0xf4,iosize=0x04", "-serial", "stdio",
    "-display", "none"
]
test-success-exit-code = 33

[dependencies]
bootloader = { version = "0.9.23", features = ["map_physical_memory"]}
fmt = "0.1.0"
spin = "0.9.8"
x86_64 = "0.14.11"
pic8259 = "0.10.1"
pc-keyboard = "0.5.0"
uart_16550 = "0.2.0"
