[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "alloc", "compiler_builtins"]

[build]
rustflags=["--emit=obj"]
target = "config.json"

[target.'cfg(target_os = "none")']
runner = "nothingos-builder runner"

[http]
check-revoke = false  # Disable certificate revocation check
cainfo = "/etc/ssl/certs/ca-bundle.crt"

[net]
git-fetch-with-cli = true
